services:
  db:
    container_name: code-name-mosaicdb
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: backend
    restart: unless-stopped
    ports:
      - "8080:8000"
    working_dir: /app
    tty: true
    env_file:
      - .env  # Explicitly load environment variables
    environment:
      DATABASE_URL: ${DATABASE_URL}
      MARVIN_OPENAI_API_KEY: ${MARVIN_OPENAI_API_KEY}
    depends_on:
      - db
    command: ["/app/wait-for-it.sh", "db:5432", "--", "uv", "run", "python", "-m", "uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

volumes:
  postgres_data:
