services:
  db:
    container_name: code-name-mosaicdb
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Bobby11
      POSTGRES_DB: codename-mindmosaicdb
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: backend
    restart: unless-stopped
    ports:
      - "8080:8000"
    working_dir: /root/fastapi
    tty: true
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=codename-mindmosaicdb
      - DB_USER=postgres
      - DB_PASSWORD=Bobby11
    volumes:
      - ./fastapi:/root/fastapi
    depends_on:
      - db
    command:
      - "/bin/sh"
      - "-c"
      - "./wait-for-it.sh db:5432 -- uvicorn main:app --reload --host 0.0.0.0 --port 8000"

volumes:
  postgres_data:
